export const MESSAGES = {
  SUCCESS: {
    OTP_SENT: 'OTP sent to email',
    OTP_RESENT: 'OTP resent successfully',
    OTP_VERIFIED: 'OTP verified successfully',
    LOGIN_SUCCESS: 'Login successful',
    TOKEN_REFRESHED: 'Access token refreshed successfully',
    LOGOUT_SUCCESS: 'Logout successful',
    PASSWORD_RESET_SENT: 'Password reset email sent',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully',
    PASSWORD_UPDATE_SUCCESS: 'Password updated successfully',
    PASSWORD_RESET_SUCCESSFULLY: 'Password reset successfully; Please Log in',
    PROFILE_UPDATED: 'Profile updated successfully',
    CAR_UPLOADED: 'Car uploaded successfully',
    CARS_FETCHED: 'Cars fetched successfully',
    BOOKINGS_FETCHED: 'Bookings fetched successfully',
    PROFILE_FETCHED: 'Profile fetched successfully',
    ID_PROOF_UPDATED: 'ID Proof updated successfully',
    STATUS_UPDATED: 'Status updated successfully',
    OWNERS_FETCHED: 'Car owners fetched successfully',
    CAR_UPDATED: 'Car Detail Updated Successfully',
    CAR_DELETED: 'Car Deleted Successfully',
    CUSTOMERS_FETCHED: 'Customers fetched successfully',
    COMPLETED_REGISTRATION_FORM: 'Completed Registration Form',
    STATS_RETRIEVED: 'Vroom Stats Retrieved Succcessfully',
    AVAILABLE_DATES_UPDATED: 'Availability updated successfully',
  },
  ERROR: {
    MISSING_FIELDS: 'Required fields are missing',
    EMAIL_REQUIRED: 'Email is required',
    INVALID_CREDENTIALS: 'Invalid email or password',
    UNAUTHORIZED: 'Unauthorized access',
    CUSTOMER_NOT_FOUND: 'Customer not found',
    OWNER_NOT_FOUND: 'Car Owner not found',
    FORBIDDEN: 'Access forbidden',
    PROFILE_NOT_FOUND: 'Owner profile not found',
    NO_OWNER_ID_FOUND: 'Forbidden: No car owner ID found',
    NO_CUSTOMER_ID_FOUND: 'Forbidden: No customer ID found',
    NO_UPDATE_DATA: 'No data provided to update.',
    NOT_FOUND: 'Resource not found',
    SERVER_ERROR: 'Something went wrong. Please try again later',
    OTP_INVALID: 'Invalid OTP',
    NO_REFRESH_TOKEN: 'No refresh token found',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    ADMIN_NOT_FOUND: 'Admin not found',
    MISSING_COORDINATES: 'Latitude and longitude are required',
    MISSING_CAR_ID: 'Car ID is required',
    MISSING_PAYMENT_INTENT: 'Payment Intent ID is required',
    INVALID_PAGE_OR_LIMIT: 'Invalid page or limit',
    RECEIPT_NOT_FOUND: 'Receipt Not Found',
    INVALID_BOOKING_ID: 'Invalid Booking ID',
    BOOKING_NOT_FOUND: 'Booking not found',
    WALLET_NOT_FOUND: 'Wallet not found',
    NO_UNAVAILABLE_DATES: 'UnavailableDates must be an array of strings',
    NO_ADMIN_COMPLAINT: 'Admins cannot create complaints',
    WALLET_BALANCE: 'Insufficient wallet balalnce',
  },
};
